<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Company>Umbraco HQ</Company>
    <Authors>Umbraco</Authors>
    <Copyright>Copyright © Umbraco $([System.DateTime]::Today.ToString('yyyy'))</Copyright>
    <Product>Umbraco Engage Automate</Product>
    <NeutralLanguage>en-US</NeutralLanguage>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- NuGet -->
  <PropertyGroup>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
    <PackageProjectUrl>https://github.com/umbraco/Umbraco.Engage.Automate</PackageProjectUrl>
    <RepositoryUrl>https://github.com/umbraco/Umbraco.Engage.Automate</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>logo-128.png</PackageIcon>
    <PackageTags>umbraco;engage;automate;automation;personalization</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="$(MSBuildThisFileDirectory)assets\logo-128.png" Pack="true" PackagePath="" Visible="false" />
  </ItemGroup>
</Project>
